/*
 * generated by Xtext 2.21.0
 */
package su.nsk.iae.post.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import su.nsk.iae.post.ide.contentassist.antlr.internal.InternalPoSTParser;
import su.nsk.iae.post.services.PoSTGrammarAccess;

public class PoSTParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PoSTGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PoSTGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getGlobalVarDeclarationAccess().getAlternatives_2(), "rule__GlobalVarDeclaration__Alternatives_2");
			builder.put(grammarAccess.getDataTypeNameAccess().getAlternatives(), "rule__DataTypeName__Alternatives");
			builder.put(grammarAccess.getNumericTypeNameAccess().getAlternatives(), "rule__NumericTypeName__Alternatives");
			builder.put(grammarAccess.getIntegerTypeNameAccess().getAlternatives(), "rule__IntegerTypeName__Alternatives");
			builder.put(grammarAccess.getConstantAccess().getAlternatives(), "rule__Constant__Alternatives");
			builder.put(grammarAccess.getNumericLiteralAccess().getAlternatives(), "rule__NumericLiteral__Alternatives");
			builder.put(grammarAccess.getGreetingAccess().getGroup(), "rule__Greeting__Group__0");
			builder.put(grammarAccess.getVarInitDeclarationAccess().getGroup(), "rule__VarInitDeclaration__Group__0");
			builder.put(grammarAccess.getVarListAccess().getGroup(), "rule__VarList__Group__0");
			builder.put(grammarAccess.getVarListAccess().getGroup_1(), "rule__VarList__Group_1__0");
			builder.put(grammarAccess.getInputVarDeclarationAccess().getGroup(), "rule__InputVarDeclaration__Group__0");
			builder.put(grammarAccess.getInputVarDeclarationAccess().getGroup_1(), "rule__InputVarDeclaration__Group_1__0");
			builder.put(grammarAccess.getOutputVarDeclarationAccess().getGroup(), "rule__OutputVarDeclaration__Group__0");
			builder.put(grammarAccess.getOutputVarDeclarationAccess().getGroup_1(), "rule__OutputVarDeclaration__Group_1__0");
			builder.put(grammarAccess.getInputOutputVarDeclarationAccess().getGroup(), "rule__InputOutputVarDeclaration__Group__0");
			builder.put(grammarAccess.getInputOutputVarDeclarationAccess().getGroup_1(), "rule__InputOutputVarDeclaration__Group_1__0");
			builder.put(grammarAccess.getVarDeclarationAccess().getGroup(), "rule__VarDeclaration__Group__0");
			builder.put(grammarAccess.getVarDeclarationAccess().getGroup_2(), "rule__VarDeclaration__Group_2__0");
			builder.put(grammarAccess.getTempVarDeclarationAccess().getGroup(), "rule__TempVarDeclaration__Group__0");
			builder.put(grammarAccess.getTempVarDeclarationAccess().getGroup_1(), "rule__TempVarDeclaration__Group_1__0");
			builder.put(grammarAccess.getExternalVarDeclarationAccess().getGroup(), "rule__ExternalVarDeclaration__Group__0");
			builder.put(grammarAccess.getExternalVarDeclarationAccess().getGroup_1(), "rule__ExternalVarDeclaration__Group_1__0");
			builder.put(grammarAccess.getExternalVarInitDeclarationAccess().getGroup(), "rule__ExternalVarInitDeclaration__Group__0");
			builder.put(grammarAccess.getGlobalVarDeclarationAccess().getGroup(), "rule__GlobalVarDeclaration__Group__0");
			builder.put(grammarAccess.getGlobalVarDeclarationAccess().getGroup_2_0(), "rule__GlobalVarDeclaration__Group_2_0__0");
			builder.put(grammarAccess.getGlobalVarDeclarationAccess().getGroup_2_1(), "rule__GlobalVarDeclaration__Group_2_1__0");
			builder.put(grammarAccess.getGlobalVarInitDeclarationAccess().getGroup(), "rule__GlobalVarInitDeclaration__Group__0");
			builder.put(grammarAccess.getTimeLiteralAccess().getGroup(), "rule__TimeLiteral__Group__0");
			builder.put(grammarAccess.getSingleElementTypeDeclarationAccess().getGroup(), "rule__SingleElementTypeDeclaration__Group__0");
			builder.put(grammarAccess.getSimpleSpecificationInitAccess().getGroup(), "rule__SimpleSpecificationInit__Group__0");
			builder.put(grammarAccess.getSimpleSpecificationInitAccess().getGroup_2(), "rule__SimpleSpecificationInit__Group_2__0");
			builder.put(grammarAccess.getConstantAccess().getGroup_2(), "rule__Constant__Group_2__0");
			builder.put(grammarAccess.getSignedIntegerAccess().getGroup(), "rule__SignedInteger__Group__0");
			builder.put(grammarAccess.getIntegerLiteralAccess().getGroup(), "rule__IntegerLiteral__Group__0");
			builder.put(grammarAccess.getIntegerLiteralAccess().getGroup_0(), "rule__IntegerLiteral__Group_0__0");
			builder.put(grammarAccess.getRealLiteralAccess().getGroup(), "rule__RealLiteral__Group__0");
			builder.put(grammarAccess.getRealLiteralAccess().getGroup_0(), "rule__RealLiteral__Group_0__0");
			builder.put(grammarAccess.getModelAccess().getGreetingsAssignment(), "rule__Model__GreetingsAssignment");
			builder.put(grammarAccess.getGreetingAccess().getNameAssignment_1(), "rule__Greeting__NameAssignment_1");
			builder.put(grammarAccess.getSymbolicVariableAccess().getNameAssignment(), "rule__SymbolicVariable__NameAssignment");
			builder.put(grammarAccess.getVarInitDeclarationAccess().getVarListAssignment_0(), "rule__VarInitDeclaration__VarListAssignment_0");
			builder.put(grammarAccess.getVarInitDeclarationAccess().getSpecAssignment_2(), "rule__VarInitDeclaration__SpecAssignment_2");
			builder.put(grammarAccess.getVarListAccess().getVarsAssignment_0(), "rule__VarList__VarsAssignment_0");
			builder.put(grammarAccess.getVarListAccess().getVarsAssignment_1_1(), "rule__VarList__VarsAssignment_1_1");
			builder.put(grammarAccess.getInputVarDeclarationAccess().getVarsAssignment_1_0(), "rule__InputVarDeclaration__VarsAssignment_1_0");
			builder.put(grammarAccess.getOutputVarDeclarationAccess().getVarsAssignment_1_0(), "rule__OutputVarDeclaration__VarsAssignment_1_0");
			builder.put(grammarAccess.getInputOutputVarDeclarationAccess().getVarsAssignment_1_0(), "rule__InputOutputVarDeclaration__VarsAssignment_1_0");
			builder.put(grammarAccess.getVarDeclarationAccess().getConstAssignment_1(), "rule__VarDeclaration__ConstAssignment_1");
			builder.put(grammarAccess.getVarDeclarationAccess().getVarsAssignment_2_0(), "rule__VarDeclaration__VarsAssignment_2_0");
			builder.put(grammarAccess.getTempVarDeclarationAccess().getVarsAssignment_1_0(), "rule__TempVarDeclaration__VarsAssignment_1_0");
			builder.put(grammarAccess.getExternalVarDeclarationAccess().getVarsAssignment_1_0(), "rule__ExternalVarDeclaration__VarsAssignment_1_0");
			builder.put(grammarAccess.getExternalVarInitDeclarationAccess().getVarListAssignment_0(), "rule__ExternalVarInitDeclaration__VarListAssignment_0");
			builder.put(grammarAccess.getExternalVarInitDeclarationAccess().getTypeAssignment_2(), "rule__ExternalVarInitDeclaration__TypeAssignment_2");
			builder.put(grammarAccess.getGlobalVarDeclarationAccess().getConstAssignment_1(), "rule__GlobalVarDeclaration__ConstAssignment_1");
			builder.put(grammarAccess.getGlobalVarDeclarationAccess().getVarsSimpleAssignment_2_0_0(), "rule__GlobalVarDeclaration__VarsSimpleAssignment_2_0_0");
			builder.put(grammarAccess.getGlobalVarDeclarationAccess().getVarsAsAssignment_2_1_0(), "rule__GlobalVarDeclaration__VarsAsAssignment_2_1_0");
			builder.put(grammarAccess.getGlobalVarInitDeclarationAccess().getVarListAssignment_0(), "rule__GlobalVarInitDeclaration__VarListAssignment_0");
			builder.put(grammarAccess.getGlobalVarInitDeclarationAccess().getLocationAssignment_2(), "rule__GlobalVarInitDeclaration__LocationAssignment_2");
			builder.put(grammarAccess.getGlobalVarInitDeclarationAccess().getTypeAssignment_4(), "rule__GlobalVarInitDeclaration__TypeAssignment_4");
			builder.put(grammarAccess.getTimeLiteralAccess().getIntervalAssignment_3(), "rule__TimeLiteral__IntervalAssignment_3");
			builder.put(grammarAccess.getSingleElementTypeDeclarationAccess().getNameAssignment_0(), "rule__SingleElementTypeDeclaration__NameAssignment_0");
			builder.put(grammarAccess.getSingleElementTypeDeclarationAccess().getTypeAssignment_2(), "rule__SingleElementTypeDeclaration__TypeAssignment_2");
			builder.put(grammarAccess.getSimpleSpecificationInitAccess().getTypeAssignment_1(), "rule__SimpleSpecificationInit__TypeAssignment_1");
			builder.put(grammarAccess.getSimpleSpecificationInitAccess().getValueAssignment_2_1(), "rule__SimpleSpecificationInit__ValueAssignment_2_1");
			builder.put(grammarAccess.getSignedIntegerAccess().getSigAssignment_0(), "rule__SignedInteger__SigAssignment_0");
			builder.put(grammarAccess.getSignedIntegerAccess().getValueAssignment_1(), "rule__SignedInteger__ValueAssignment_1");
			builder.put(grammarAccess.getIntegerLiteralAccess().getTypeAssignment_0_0(), "rule__IntegerLiteral__TypeAssignment_0_0");
			builder.put(grammarAccess.getIntegerLiteralAccess().getValueAssignment_1(), "rule__IntegerLiteral__ValueAssignment_1");
			builder.put(grammarAccess.getRealLiteralAccess().getTypeAssignment_0_0(), "rule__RealLiteral__TypeAssignment_0_0");
			builder.put(grammarAccess.getRealLiteralAccess().getDivAssignment_1(), "rule__RealLiteral__DivAssignment_1");
			builder.put(grammarAccess.getRealLiteralAccess().getModAssignment_3(), "rule__RealLiteral__ModAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PoSTGrammarAccess grammarAccess;

	@Override
	protected InternalPoSTParser createParser() {
		InternalPoSTParser result = new InternalPoSTParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PoSTGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PoSTGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
