/**
 * generated by Xtext 2.21.0
 */
package su.nsk.iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.RealLiteral#getDiv <em>Div</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.RealLiteral#getMod <em>Mod</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getRealLiteral()
 * @model
 * @generated
 */
public interface RealLiteral extends NumericLiteral
{
  /**
   * Returns the value of the '<em><b>Div</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Div</em>' containment reference.
   * @see #setDiv(SignedInteger)
   * @see su.nsk.iae.post.poST.PoSTPackage#getRealLiteral_Div()
   * @model containment="true"
   * @generated
   */
  SignedInteger getDiv();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.RealLiteral#getDiv <em>Div</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Div</em>' containment reference.
   * @see #getDiv()
   * @generated
   */
  void setDiv(SignedInteger value);

  /**
   * Returns the value of the '<em><b>Mod</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mod</em>' attribute.
   * @see #setMod(int)
   * @see su.nsk.iae.post.poST.PoSTPackage#getRealLiteral_Mod()
   * @model
   * @generated
   */
  int getMod();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.RealLiteral#getMod <em>Mod</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mod</em>' attribute.
   * @see #getMod()
   * @generated
   */
  void setMod(int value);

} // RealLiteral
